# .github/workflows/ci.yml

name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      BROWSER: "chromium"
      SCRAPE_URL: "https://www.prydwen.gg/star-rail/characters/"
      SCRAPE_LIMIT: None
      DB_URL: "sqlite:///hsr.db"

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
  
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q